# Generated by Django 2.2.6 on 2019-10-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2055)),
                ('time', models.DateTimeField(auto_now=True)),
                ('post', models.TextField()),
            ],
        ),
    ]
