# Generated by Django 2.2.6 on 2019-10-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
