# Generated by Django 2.2.6 on 2019-10-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191007_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
