# Generated by Django 2.2.6 on 2019-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191007_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='empty',
            field=models.IntegerField(default=1),
        ),
    ]
